// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dungeons} from '../models';

export function DungeonToString():Promise<string>;

export function GenerateDungeon():Promise<string>;

export function GetRoomStats():Promise<dungeons.Room>;

export function ProgressInDungeon():Promise<void>;

export function WipeDungeon():Promise<void>;
