// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DungeonToString() {
  return window['go']['main']['App']['DungeonToString']();
}

export function GenerateDungeon() {
  return window['go']['main']['App']['GenerateDungeon']();
}

export function GetRoomStats() {
  return window['go']['main']['App']['GetRoomStats']();
}

export function ProgressInDungeon() {
  return window['go']['main']['App']['ProgressInDungeon']();
}
